### ISSUE TITLE
filter item based on $select query, before inserting it when onItemCreated/Updated...

### ISSUE THREAD

**Issue by beeplin** [t2t2/vue-syncers-feathers#15]
now it's like this in `collection.js`:

``` js
    onItemCreated(item) {

        if (this._itemMatches(item)) {
            this._set(item[this._id], item)
        }
    }
    onItemUpdated(item) {
        if (this._itemMatches(item)) {
            this._set(item[this._id], item)
        } else if (item[this._id] in this.state) {
            this._remove(item[this._id])
        }
    }
```

but if a `$select` option is present in the `query` object, we need to filter the `item` according to the `$select` before inserting it into the collection. Otherwise it would be messed up. For example, when `query` has `$select: ['email']`, it would be like this: 

``` js
{
  { "_id": "5803b6d6021477f3588912fd", "email": "cvd" },
  { "_id": "580385dbf5c3d0bcee8abbd8", "email": "hahaha" },
  { "_id": "580590bf4a82c9551c0d4921", "email": "zzz" },
  { "__v": 0, "username": "new", "email": "new", "isVerified": false, "verifyToken": "815d9972ddc6708d44c1ab957aa75e", "_id": "5806cae4b6f2432d04203aa5", "updatedAt": "2016-10-19T01:22:44.563Z", "createdAt": "2016-10-19T01:22:44.563Z" }
}
```

**Comment by beeplin** [comment]
BTW the `matcher` function from `feathers-commons` currently doesn't support `$select` correctly either. I have committed a [PR](https://github.com/feathersjs/feathers-commons/pull/33) here:

**Comment by t2t2** [comment]
Started work on it in [feature-$select](https://github.com/t2t2/vue-syncers-feathers/tree/feature-%24select) branch, merged once a bug in feathers-memory is fixed for tests

**Comment by beeplin** [comment]
another way to do this is to **always reload the syncer when created/updated/patched/removed event received**. Just like what [feathers-reactive](https://github.com/feathersjs/feathers-reactive) does when setting `listStrategy` to `'always'`. This way not only supports $select but also $limit, $skip, and $sort. But the cost is also big: another whole-list network request/response, just for putting a new item in the right position in a collection. 

I am not sure if it's worth having a new option like `reload: always` when declaring the syncer, for dealing with these very edge cases.

And to reduce the cost of calling `find` from client (imagine 1000 users are connected via socketio, and after a `created` event sent to them, 1000 reload requests are flushing the server....), an alternate way is to do this reloading on the server, right in feathers' event filters. But that's another back-end story and cannot be controlled from front end.
