### ISSUE TITLE
add callback to syncers?

### ISSUE THREAD

**Issue by beeplin** [t2t2/vue-syncers-feathers#17]
I understand that an `itemSyncer` is actually an automatic `get`, and a `collectionSyncer` is an automatic `find`, but it seems currently it lacks callback params, so we cannot do something after the authomatic get/find is done or failed. 

I suggest that in the `sync` option, allow users to pass in a `success` and a `failure` callback, so make the syncers can do all things `find` and `get` can do. Just like this: 

``` js
new Vue {
  data: ...,
  sync: {
    item: {
      service: 'xxx',
      id: 'xxxxxx',
      success: (data) => {
        do something;
      },
    collection: {
      service: 'xxx',
      query: { ... },
      failure: (error) => {
        do something;
      }
    }
  }
}
```

Or any better names or better ways to do this?

**Comment by t2t2** [comment]
[Events?](https://github.com/t2t2/vue-syncers-feathers#instance-events)

[example in tests](https://github.com/t2t2/vue-syncers-feathers/blob/master/test/item.test.js#L38)

**Comment by beeplin** [comment]
Hmmm, events could do the job. While, those developers who are already familiar with the ordinary feathers syntax might feel better if an additional callback-style interface is provided. Let's compare the two syntax:

``` js
new Vue {
  sync: {
    item: {
      service: 'xxx',
      id: 'xxxx',
      success: (data) => { 
        console.log(data)
      }
    }
  }
}
```

or: 

``` js
new Vue {
  sync: {
    item: {
      service: 'xxx',
      id: 'xxxx'
    }
  }
  ...
  inSomeHooksOrMethods: {
    this.$on('syncer-loaded', (path, error) => {
      if (path === 'item') {
        console.log(this.item)
      }
    }
  }
}   
```

I feel the event way separates the declaration of the syncer and it's behavior apart, making it a little big hard to read, and is not that concise.

**Comment by t2t2** [comment]
Yeah that's way better for that use

Regarding interface, I feel like `loaded/error` would be better so it matches the event name, or `onLoaded/onError` so it's clearer from name that it's a callback

**Comment by beeplin** [comment]
yeah I prefer `loaded/error`.
