### ISSUE TITLE
proposal to make it 'real two-way sync'

### ISSUE THREAD

**Issue by beeplin** [t2t2/vue-syncers-feathers#8]
I really like this plugin and use it a lot in my project. But there is still a pity that it doesn't really 'sync' between back-end feathers data providers and front-end vue syncers. Actually it's better to be called 'automatical loader' rather than 'syncer', since we don't have **a concise syntax to make the syncers able to write data back to backend and then refresh itself when succeeded**. There is an awkward `this.$feathers.services('xxx').create/update/patch/remove` for writing data back, but I still have no idea how to let the syncer 'resync' itself after the writing is done without reloading the whole vue component. 

So here is my proposal to improve:
1. give every syncer additional methods to proxy `this.$feathers.services` behaviors, like this(assuming the syncer name is `users`):

``` javascript
    this.users.create = this.$services.users.create.bind(this.$services.users)
    this.users.update = this.$services.users.update.bind(this.$services.users)
    this.users.patch = this.$services.users.patch.bind(this.$services.users)
    this.users.remove = this.$services.users.remove.bind(this.$services.users)
```
1. give the syncer another new method, say, `refresh` or something, to manually **re-sync or re-load** itself from server whenever the four methods above has completed and promise has been resolved. 

Again, very nice works, thanks, @t2t2 ~

**Comment by beeplin** [comment]
By doing this, the syncer in the vue component become a truly real-time 'mirror' between front and back. People just declare it in the `sync` option, and then let it modify itself, say, create new sub items inside itself, or update/patch/remove its sub items. When doing these  modifications, after the flash of `$loadingSyncers`, all data are synced, both front and back. That would be the most natural way to link vue with feathers, I guess.

**Comment by beeplin** [comment]
Additionally, when doing create/update/patch/remove on syncers, before the confirmation get back from server, we also could make the change effective so the UI shows the change immediately. Once the confirmation arrives, do nothing; in case of serving failing to do the change, just roll back to the original (real) state.

this is basically meteor's idea of 'optimistic ui'. I guess we could achieve this easily if you think it valuable, but it is totally optional. :)

**Comment by beeplin** [comment]
ok I figured out that I can use `this._syncers[name]._loadNewState()` to reload data.

**Comment by beeplin** [comment]
And then I realized that, as long as socket.io event emitter is not filtered on the server side, we don't need to re-sync by hand. It's automatically done. Cool. I previously turn off the emitters for debug reasons and totally forgot about that. :(

So things are simple now: what's needed to do is to just make proxies/alias names to write back to server.

**Comment by t2t2** [comment]
> ``` js
> this.users.create = this.$services.users.create.bind(this.$services.users)
> ```

Hmm this could have some conflicts in maps (if (for some reason, maybe like if idField is set to slug or something) there's something with same id)

Something that I've been doing is:

``` js
// in bootstrapping
Vue.prototype.$feathers = feathers
Vue.prototype.$service = function (name) {
    return feathers.service(name)
}
```

``` js
// using, es2017 syntax
try {
    await this.$service('users').create(this.objectToCreate)
} catch(error) {
    this.errors = error
}
```

([taken from](https://github.com/t2t2/draftraptor/blob/master/src/frontend/components/admin/Teams.vue#L147))

If this is a nice enough solution it could be added to a mixin for now (was thinking of including an optional mixin that does some remapping like this.$loading -> this.$loadingSyncers)

**Comment by beeplin** [comment]
could you elaborate the possibilities of conflicts? I don't quite get it. 

I just created a new plugin, wrapped yours a little, and get my ideas integrated: [vue-feathers-sync](https://github.com/beeplin/vue-feathers-sync/). Just for my own projects, maybe. So I am keen to know if there would be some big potential problems ...

And thank you for this, again. :)

**Comment by t2t2** [comment]
Basically anything where idField's value could be create/update/patch/remove, it's a super edge case that's really really unlikely to happen, would have to do something like this:

``` js
// server side
app.service('settings', memory({
    id: 'key',
    store: {
        usefulSetting: {
            key: 'usefulSetting',
            value: 'this value is useful to have'
        },
        update: {
            key: 'update', // idk, some sort of update interval?
            value: 500
        }
    }
})
```

``` js
// frontend, component
export default {
    sync: {
        settings: {
            service: 'settings',
            idField: 'key'
        }
    }
}

this.settings.usefulSetting.value // would work, though ugly
this.settings.update.value // would break
```

Again, really really really unlikely and you'll probably won't have a problem with it

**Comment by beeplin** [comment]
got it. In practice we use mongoDB's objectId is key, so indeed it's not quite possible to have an id value 'update'. :)
